# 本地开发环境配置
server:
  port: 2333

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/talent_item
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
    password:


logging:
  level:
    item: debug
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

com:
  kingdee:
    talent:
      item:
        swagger:
          enable: true

