# 测试环境配置
server:
  port: 2333

spring:
  datasource:
    url: jdbc:mysql://233.233.233.233:3306/scaffold_item
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 233.233.233.233
    port: 10086
    password: 23333

logging:
  level:
    item: DEBUG

com:
  isaacbao:
    scaffold:
      item:
        swagger:
          enable: true